[[news]]
date = "2025-09"
content = "🎓 Started my PhD program at UC Irvine, advised by Prof. Athina Markopoulou."

[[news]]
date = "2025-08"
content = "✈️ Received the IMC Travel Grant."

[[news]]
date = "2025-08"
content = "🎉 Our paper was accepted to IEEE S&P 2026."

[[news]]
date = "2025-05"
content = "🎓 Graduated from Washington University in St. Louis."

[[news]]
date = "2025-04"
content = "🎉 Our paper was accepted to IMC 2025."
